# Uncomment the next line to define a global platform for your project

source 'http://gitlab/iOS/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
target 'RxMVVM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

end
